import cron from "node-cron";
import ReminderModel from "../models/Reminder.model";
import WebinarModel from "../models/Webinar.model";
import { sendMail } from "./mailer";
import { generateReminderEmailTemplate } from "./emailTemplates";
import { logError, logInfo } from "./logger";
import { SimpleCertificateService } from "./simpleCertificateService";

const sendReminderEmails = async () => {
  try {
    const now = new Date();
    const fiveMinutesFromNow = new Date(now.getTime() + 5 * 60 * 1000);

    // Find reminders that should be sent in the next 5 minutes
    const dueReminders = await ReminderModel.find({
      reminderTime: { $gte: now, $lte: fiveMinutesFromNow },
      isEmailSent: false,
    })
      .populate("userId", "firstName lastName email")
      .populate("webinarId", "title date description");

    if (dueReminders.length === 0) {
      return;
    }

    logInfo(`Found ${dueReminders.length} reminders to send`);

    for (const reminder of dueReminders) {
      try {
        const user = reminder.userId as any;
        const webinar = reminder.webinarId as any;

        if (!user || !webinar) {
          logError(
            `Missing user or webinar data for reminder: ${reminder._id.toString()}`
          );
          continue;
        }

        const subject = `Reminder: ${webinar.title}`;
        const webinarDate = new Date(webinar.date).toLocaleString();

        const emailTemplate = generateReminderEmailTemplate({
          firstName: user.firstName,
          webinarTitle: webinar.title,
          webinarDate,
          webinarDescription: webinar.description,
        });

        await sendMail({
          to: user.email,
          subject,
          html: emailTemplate,
        });

        // Mark reminder as sent
        reminder.isEmailSent = true;
        await reminder.save();

        logInfo(
          `Reminder email sent to ${user.email} for webinar: ${webinar.title}`
        );
      } catch (emailError) {
        logError(
          `Failed to send reminder email for reminder ${reminder._id}:`,
          emailError as Error
        );
      }
    }
  } catch (error) {
    logError("Error in sendReminderEmails:", error as Error);
  }
};

const sendWebinarStartReminders = async () => {
  try {
    // This function could be used for immediate webinar start notifications
    // Implementation can be added based on business requirements
    logInfo("Checking for webinar start reminders...");
  } catch (error) {
    logError("Error in sendWebinarStartReminders:", error as Error);
  }
};

const cleanupOldReminders = async () => {
  try {
    const yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000);

    const result = await ReminderModel.deleteMany({
      reminderTime: { $lt: yesterday },
      isEmailSent: true,
    });

    if (result.deletedCount > 0) {
      logInfo(`Cleaned up ${result.deletedCount} old reminders`);
    }
  } catch (error) {
    logError("Error in cleanupOldReminders:", error as Error);
  }
};

/**
 * Auto-generate certificates for webinars that have ended
 */
const autoGenerateCertificates = async () => {
  try {
    const now = new Date();
    const thirtyMinutesAgo = new Date(now.getTime() - 30 * 60 * 1000);

    // Find webinars that ended in the last 30 minutes and haven't had certificates generated
    const eligibleWebinars = await WebinarModel.find({
      endDate: { $gte: thirtyMinutesAgo, $lte: now },
      $or: [
        { "certificateConfig.autoGenerated": { $ne: true } },
        { "certificateConfig.autoGenerated": { $exists: false } },
      ],
      "certificateConfig.isEnabled": true,
    });

    if (eligibleWebinars.length === 0) {
      return;
    }

    logInfo(
      `Found ${eligibleWebinars.length} webinars eligible for auto certificate generation`
    );

    for (const webinar of eligibleWebinars) {
      try {
        logInfo(
          `Auto-generating certificates for webinar: ${webinar.title} (${webinar._id})`
        );

        // Generate certificates for all qualified attendees
        let successCount = 0;
        let failCount = 0;

        if (webinar.attendedUsers && webinar.attendedUsers.length > 0) {
          for (const attendee of webinar.attendedUsers) {
            // Only generate for users who attended for at least 30 minutes
            if ((attendee as any).totalDuration >= 30) {
              try {
                const result =
                  await SimpleCertificateService.requestCertificateForUser(
                    (attendee as any).userId.toString(),
                    (webinar._id as any).toString()
                  );

                if (result.success) {
                  successCount++;
                } else {
                  failCount++;
                  logError(
                    `Failed to generate certificate for user ${
                      (attendee as any).userId
                    }: ${result.error}`
                  );
                }
              } catch (error) {
                failCount++;
                logError(
                  `Error generating certificate for user ${
                    (attendee as any).userId
                  }:`,
                  error as Error
                );
              }
            }
          }
        }

        if (successCount > 0) {
          logInfo(
            `Successfully initiated certificate generation for ${successCount} users in webinar ${webinar._id}`
          );

          // Mark webinar as having auto-generated certificates
          await WebinarModel.findByIdAndUpdate(webinar._id, {
            "certificateConfig.autoGenerated": true,
            "certificateConfig.generatedAt": new Date(),
          });
        }

        if (failCount > 0) {
          logError(
            `Failed to generate certificates for ${failCount} users in webinar ${webinar._id}`
          );
        }
      } catch (error) {
        logError(
          `Error generating certificates for webinar ${webinar._id}:`,
          error as Error
        );
      }
    }
  } catch (error) {
    logError("Error in autoGenerateCertificates:", error as Error);
  }
};

/**
 * Check and update certificate generation job statuses
 */
const monitorCertificateJobs = async () => {
  try {
    // This could be expanded to check job statuses and send notifications
    // For now, just log that the monitor is running
    logInfo("Certificate job monitoring check completed");
  } catch (error) {
    logError("Error in monitorCertificateJobs:", error as Error);
  }
};

export const startReminderCron = () => {
  // Send reminder emails every minute
  cron.schedule("*/1 * * * *", sendReminderEmails, {
    timezone: "UTC",
  });

  // Clean up old reminders daily at midnight
  cron.schedule("0 0 * * *", cleanupOldReminders, {
    timezone: "UTC",
  });

  logInfo("Reminder cron jobs started successfully");
};

export const startCertificateCron = () => {
  // Auto-generate certificates every 5 minutes for recently ended webinars
  cron.schedule("*/5 * * * *", autoGenerateCertificates, {
    timezone: "UTC",
  });

  // Monitor certificate job statuses every 10 minutes
  cron.schedule("*/10 * * * *", monitorCertificateJobs, {
    timezone: "UTC",
  });

  logInfo("Certificate cron jobs started successfully");
};

export const startAllCronJobs = () => {
  startReminderCron();
  startCertificateCron();
  logInfo("All cron jobs started successfully");
};
